import type { Shorthands, Tokens } from "./";

export const tokens: Tokens = {
  space: [0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64],
  fontFamily: {
    sans: "sans-serif",
    serif: "serif",
    mono: "monospace",
  },
  fontSize: ["3rem", "3rem", "2.2rem", "1.8rem", "1.4rem", "1rem", "0.875rem"],
  fontWeight: [
    "0",
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
    "1000",
  ],
  lineHeight: [1.1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
};

export const shorthands: Shorthands = {
  d: "display",
  w: "width",
  h: "height",
  c: "color",
  bg: "background",
  m: ["marginTop", "marginBottom", "marginLeft", "marginRight"],
  mt: "marginTop",
  mb: "marginBottom",
  ml: "marginLeft",
  mr: "marginRight",
  my: ["marginTop", "marginBottom"],
  mx: ["marginLeft", "marginRight"],
  p: ["paddingTop", "paddingBottom", "paddingLeft", "paddingRight"],
  pt: "paddingTop",
  pb: "paddingBottom",
  pl: "paddingLeft",
  pr: "paddingRight",
  py: ["paddingTop", "paddingBottom"],
  px: ["paddingLeft", "paddingRight"],
  z: "zIndex",
  fs: "fontSize",
  ff: "fontFamily",
  fw: "fontWeight",
  lh: "lineHeight",
  ta: "textAlign",
  va: "verticalAlign",
};
